name: 'Content list'
description: 'Output a folder content list'
branding:
  icon: 'book'
  color: 'yellow'
inputs:
  owner:
    description: 'Owner'
    required: true
  repo:
    description: 'Repository'
    required: true
  path:
    description: 'Path'
    required: true
    default: '/'
outputs:
  result:
    description: 'Content list'
runs:
  using: 'node12'
  main: 'index.js'
